Repository portworx/torpedo, pull requests merged in 2020-07, with the labels that each got.

#508 Add resource limit for rabbitmq-io container
  drivers/scheduler/k8s/specs/rabbitmq/px-rabbitmq-app.yml
Labels: ready-for-review

#513 Remove make vendor from travis
  .travis.yml
  go.mod
  go.sum
  vendor/github.com/LINBIT/golinstor/LICENSE
  vendor/github.com/LINBIT/golinstor/client/apicallerror.go
  vendor/github.com/LINBIT/golinstor/client/cache.go
  vendor/github.com/LINBIT/golinstor/client/client.go
  vendor/github.com/LINBIT/golinstor/client/controller.go
  vendor/github.com/LINBIT/golinstor/client/controllerconfig.go
  vendor/github.com/LINBIT/golinstor/client/encryption.go
  vendor/github.com/LINBIT/golinstor/client/node.go
  vendor/github.com/LINBIT/golinstor/client/openflex.go
  vendor/github.com/LINBIT/golinstor/client/option.go
  vendor/github.com/LINBIT/golinstor/client/physicalstorage.go
  vendor/github.com/LINBIT/golinstor/client/resource.go
  vendor/github.com/LINBIT/golinstor/client/resourcedefinition.go
  vendor/github.com/LINBIT/golinstor/client/resourcegroup.go
  vendor/github.com/LINBIT/golinstor/client/storagepooldefinition.go
  vendor/github.com/moul/http2curl/.gitignore
  vendor/github.com/moul/http2curl/.travis.yml
  vendor/github.com/moul/http2curl/LICENSE
  vendor/github.com/moul/http2curl/Makefile
  vendor/github.com/moul/http2curl/README.md
  vendor/github.com/moul/http2curl/http2curl.go
  vendor/modules.txt
Labels: ready-for-review

#511 PTX-2528 add better logging for pods in torpedo
  drivers/volume/portworx/schedops/k8s-schedops.go
  tests/common.go
Labels: ready-for-review, waiting-for-dev-test-job

#502 PTX-2580 Refactor backup tests
  tests/backup/backup_test.go
  tests/backup/backup_util.go
Labels: ready-for-review

#518 Collect support bundle in case of scheduler upgrade test failures
  tests/scheduler_upgrade/scheduler_upgrade_test.go
Labels: ready-for-review

#519 [PTX-2644] Use latest px-backup api proto to include kubeconfig in clusterInspect response
  go.mod
  go.sum
  tests/backup/backup_test.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.pb.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.pb.gw.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.proto
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.swagger.json
  vendor/github.com/portworx/sched-ops/k8s/apps/statefulsets.go
  vendor/modules.txt
Labels: ready-for-review

#517 Improvements in BackupCrashVolDriver test
  drivers/backup/portworx/portworx.go
  drivers/scheduler/k8s/specs/pgbench-io-portion/px-pgbench-app.yaml
  drivers/scheduler/k8s/specs/pgbench-io-portion/px-pgbench-storage.yaml
  tests/backup/backup_test.go
Labels: ready-for-review

#522 updade vendor for new sched-ops
  go.mod
  go.sum
  vendor/github.com/portworx/sched-ops/k8s/apps/deployments.go
  vendor/github.com/portworx/sched-ops/k8s/apps/replicasets.go
  vendor/modules.txt
Labels: ready-for-review, waiting-for-dev-test-job

#523 [PTX-2664] Added `nfs_v4: "true"` label for Wordpress sharedv4 PVC
  drivers/scheduler/k8s/specs/wordpress-sharedv4/storage.yaml
Labels: waiting-for-dev-test-job
