Repository portworx/torpedo, pull requests merged in 2020-06, with the labels that each got.

#492 PTX-2551 Expose portworx-service
  drivers/volume/portworx/schedops/k8s-schedops.go
Labels: ready-for-review, ready-to-merge

#500 Fix for rabbitmq-io
  drivers/scheduler/k8s/specs/rabbitmq/px-rabbitmq-app.yml
Labels: ready-for-review, ready-to-merge

#495 PTX-2559 Delete azure bucket
  tests/backup/backup_test.go
Labels: ready-for-review, ready-to-merge

#464 PTX-2229 Added autopilot upgrade test
  deployments/deploy-ssh.sh
  drivers/api/api.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  tests/autopilot/autopilot_test.go
  tests/common.go
Labels: ready-for-review

#484 PTX-2378 Add multi provider scale tests
  deployments/deploy-ssh.sh
  drivers/backup/backup.go
  drivers/backup/portworx/portworx.go
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  drivers/scheduler/spec/factory.go
  go.mod
  go.sum
  tests/backup/backup_test.go
  vendor/gopkg.in/square/go-jose.v2/jwt/claims.go
  vendor/gopkg.in/square/go-jose.v2/jwt/validation.go
Labels: ready-for-review, ready-to-merge

#501 Fix for ValidateVolumeCleanup method for cloud runs
  drivers/volume/portworx/schedops/k8s-schedops.go
Labels: waiting-for-dev-test-job

#498 Fix for k3s cluster
  drivers/volume/portworx/portworx.go
Labels: waiting-for-dev-test-job

#474 [PTX-2506] Added ScyallaDB app
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/k8s/specs/scylladb/cassandra-stress-app.yaml
  drivers/scheduler/k8s/specs/scylladb/px-scylladb-storage.yaml
  drivers/scheduler/k8s/specs/scylladb/scylla.yaml
  drivers/scheduler/k8s/specs/scylladb/scylladb-app.yaml
  tests/basic/basic_test.go
Labels: ready-for-review

#494 [PTX-2232] Added logic to validate applications restored by backup
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  drivers/volume/portworx/portworx.go
  drivers/volume/portworx/schedops/k8s-schedops.go
  tests/backup/backup_test.go
  tests/common.go
Labels: ready-for-review, waiting-for-dev-test-job
