Repository portworx/torpedo, pull requests merged in 2021-07, with the labels that each got.

#583 PB-1716: Change code to use secret instead of password str
  drivers/backup/auth.go
  drivers/backup/backup.go
Labels: ready-for-review

#584 Remove panic() from init() in backup.go
  drivers/backup/backup.go
Labels: ready-to-merge

#587 Comment out code to check pxctl status due to issues on EKS nodes
  drivers/volume/portworx/portworx.go
Labels: bug, ready-for-review

#589 PTX-3745 fix OCP collect bundle when grabbing kubelet logs
  drivers/node/node.go
  drivers/node/ssh/ssh.go
  drivers/scheduler/openshift/openshift.go
Labels: ready-for-review

#590 PTX-3766 add retry when starting upgrade
  drivers/scheduler/openshift/openshift.go
Labels: ready-for-review
