Repository portworx/torpedo, pull requests merged in 2023-11, with the labels that each got.

#1828 Fixed error handling in CreateRestoreWithValidation function
  drivers/scheduler/k8s/k8s.go
  tests/backup/backup_helper.go
Labels: ready-for-review, Px-Backup

#1830 [Kubevirt] Fixed the test case ResizeVolumeOnScheduleBackup for Kubevirt App
  drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-containerdisk-pvc.yaml
  drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-containerdisk.yaml
  drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc-datavolume.yaml
  drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc.yaml
  drivers/scheduler/k8s/specs/kubevirt-vm-pvc/kubevirt-app.yaml
  drivers/volume/portworx/schedops/k8s-schedops.go
  tests/backup/backup_helper.go
  tests/backup/backup_locked_bucket_test.go
  tests/backup/backup_portworx_test.go
Labels: ready-for-review, Px-Backup

#1829 Fixed minor go convention violations and typos
  drivers/backup/backup.go
  tests/backup/backup_helper.go
  tests/backup/backup_namespace_labelled_test.go
  tests/backup/backup_orphaned_test.go
  tests/backup/backup_rbac_test.go
  tests/backup/backup_restore_basic_test.go
  tests/backup/backup_share_test.go
  tests/backup/backup_upgrade_test.go
Labels: ready-for-review, Px-Backup, testing-in-progress

#1811 Added backup verification before restoring it in test case PXBackupEndToEndBackupAndRestoreWithUpgrade
  tests/backup/backup_upgrade_test.go
Labels: ready-for-review, Px-Backup

#1832 PB-4760:Fixed MultipleProjectsAndNamespacesBackupAndRestore where re…
  tests/backup/backup_rancher_test.go
Labels: ready-for-review, Px-Backup

#1784 Added check for backup driver in rke.go
  drivers/backup/portworx/portworx.go
  drivers/scheduler/rke/rke.go
Labels: ready-for-review, Px-Backup

#1792 TC automation[PTX-20641] RebootNodeWhileVolCreate
  tests/basic/pure_test.go
Labels: ready-for-review

#1789 TC Automation- RestartPXWhileVolCreate
  tests/basic/pure_test.go
Labels: ready-for-review

#1822 TC Automation: SSE S3 TC Automation
  drivers/node/ssh/ssh.go
  tests/backup/backup_delete_test.go
  tests/backup/backup_helper.go
  tests/backup/backup_kubevirt_test.go
  tests/backup/backup_license_test.go
  tests/backup/backup_locked_bucket_test.go
  tests/backup/backup_namespace_labelled_test.go
  tests/backup/backup_nfs_test.go
  tests/backup/backup_orphaned_test.go
  tests/backup/backup_portworx_test.go
  tests/backup/backup_rancher_test.go
  tests/backup/backup_rbac_test.go
  tests/backup/backup_resiliency_test.go
  tests/backup/backup_restore_basic_test.go
  tests/backup/backup_sanity_test.go
  tests/backup/backup_scale_test.go
  tests/backup/backup_share_test.go
  tests/backup/backup_sse_test.go
  tests/backup/backup_upgrade_test.go
  tests/common.go
Labels: ready-for-review, Px-Backup, testing-in-progress, Lib

#1823 Fixing journal error message for dmthin
  drivers/volume/common.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  tests/basic/storage_pool_test.go
Labels: ready-for-review

#1843 PB-4812: Fix pod age compare logic
  tests/backup/backup_helper.go
  tests/backup/backup_restore_basic_test.go
Labels: bug, ready-for-review, Px-Backup

#1852 PB-4839: Add `postgres-csi` to `AppRuleMaster` array
  tests/backup/backup_helper.go
Labels: bug, ready-for-review, Px-Backup

#1820 [PTX-20870] DriveAddPXDown
  tests/basic/storage_pool_test.go
Labels: ready-for-review

#1859 adding specs and test to validate proxy volumes
  drivers/scheduler/k8s/specs/nginx-proxy-deployment/px-nginx-app.yaml
  drivers/scheduler/k8s/specs/nginx-proxy-deployment/px-nginx-storage.yaml
  drivers/volume/portworx/portworx.go
  tests/basic/node_decommission_test.go
  tests/basic/volume_ops_test.go
Labels: ready-for-review

#1840 TC fix: Fixing the SSE test to pass proper appContext for restore validation
  tests/backup/backup_sse_test.go
  tests/common.go
Labels: do-not-merge, ready-for-review, Px-Backup

#1868 PTX-20400 Create Torpedo SCC for OCP cluster to allow app provisioning
  drivers/scheduler/openshift/openshift.go
  go.mod
  go.sum
  vendor/github.com/portworx/sched-ops/k8s/kubevirt/kubevirt.go
  vendor/github.com/portworx/sched-ops/k8s/openshift/securitycontextconstraints.go
  vendor/modules.txt
Labels: ready-for-review

#1862 Skip Anthos admin cluster upgrade if upgrade hops contains only one v…
  drivers/scheduler/anthos/anthos.go
  drivers/scheduler/scheduler.go
  tests/common.go
Labels: ready-for-review

#1848 GKE fix: CreateGCPBackupLocationWithContext to accept ctx
  tests/common.go
Labels: ready-for-review, Px-Backup, Lib

#1846 Fixed DeleteSharedBackupOfUserFromAdmin failure
  tests/backup/backup_orphaned_test.go
Labels: ready-for-review, Px-Backup

#1872 PB-4865: Add logic to cleanup restores
  tests/backup/backup_locked_bucket_test.go
Labels: bug, ready-for-review, Px-Backup

#1867 Adding automation for Kubevirt upgrade test
  deployments/deploy-ssh.sh
  drivers/scheduler/k8s/specs/kubevirt-dv-app/kubevirt-dv-app.yaml
  tests/backup/backup_helper.go
  tests/backup/backup_kubevirt_test.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#1882 Added inspect volume function for ibm driver which returns ErrNotSupported
  drivers/volume/ibm/ibm.go
Labels: bug, ready-for-review, Px-Backup

#1864 Fixing node decomm test for storageless node
  drivers/volume/portworx/portworx.go
  tests/basic/node_decommission_test.go
  tests/basic/storage_pool_test.go
Labels: ready-for-review

#1788 [PTX-20636] TC Automation - ResizePVCToMaxLimit
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gce/gce.go
  drivers/volume/generic_csi/generic_csi.go
  drivers/volume/ibm/ibm.go
  drivers/volume/linstor/linstor.go
  drivers/volume/portworx/portworx.go
  drivers/volume/pso/pso.go
  drivers/volume/volume.go
  tests/basic/pure_test.go
Labels: ready-to-merge

#1887 Fix kubevirt upgrade environment variable check
  tests/backup/backup_helper.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#1866 [PTX-20633] Add CreateAndDeleteMultipleVolumesInParallel
  tests/basic/pure_test.go
Labels: ready-for-review, testing-in-progress

#1879 [Anthos] Torpedo calculate incorrect time for node upgrade when multi…
  drivers/scheduler/anthos/anthos.go
Labels: ready-for-review

#1892 [PTX-21138] Fix ValidateCreateVolume
  drivers/volume/portworx/portworx.go
  tests/testTriggers.go
Labels: ready-to-merge

#1893 Assigning kube-system as debug pod namespace for non-px environments
  drivers/node/ssh/ssh.go
Labels: ready-for-review, Px-Backup

#1884 PTX-21105 Fix/improve ProfileOnlyDiags test
  drivers/volume/portworx/portworx.go
  tests/basic/telemetry_test.go
Labels: ready-for-review

#1897 Modified app deletion method for MultipleProjectsAndNamespacesBackupA…
  tests/backup/backup_rancher_test.go
Labels: ready-for-review, Px-Backup

#1904 PTX-21183 Remove debug prints
  drivers/volume/portworx/portworx.go
  tests/basic/telemetry_test.go
Labels: ready-for-review

#1888 Topic/leela/falun ptx 20629
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/k8s/specs/bonnie-sharedv4/px-bonnie-app.yml
  drivers/scheduler/scheduler.go
  pkg/pureutils/pure_types.go
  tests/basic/pure_test.go
  tests/basic/storage_pool_test.go
Labels: ready-for-review

#1907 Adding HA update error injection
  tests/basic/ha_update_test.go
  tests/basic/longevity_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-for-review

#1901 Fix torpedo pod logs getting printed on console
  deployments/deploy-pxb-cloud.sh
  deployments/deploy-ssh-taas.sh
  deployments/deploy-ssh.sh
Labels: enhancement, framework, ready-for-review, testing-in-progress

#1922 Adding more validation FA Volume detach test
  drivers/scheduler/k8s/specs/nginx-fada-deploy/px-deploy.yaml
  tests/basic/pure_test.go
Labels: ready-for-review

#1923 minor fixes for add-disk test for dmthin
  tests/basic/storage_pool_test.go
  tests/testTriggers.go
Labels: ready-for-review

#1917 PTX-21225 Do not use async sdk diags method for collecting
  tests/basic/telemetry_test.go
Labels: ready-for-review

#1925 [PTX-20619] Validate Pure Backend Volume Creation And Deletion
  drivers/volume/aws/aws.go
  drivers/volume/azure/azure.go
  drivers/volume/gce/gce.go
  drivers/volume/generic_csi/generic_csi.go
  drivers/volume/ibm/ibm.go
  drivers/volume/linstor/linstor.go
  drivers/volume/portworx/portworx.go
  drivers/volume/pso/pso.go
  drivers/volume/volume.go
  go.mod
  go.sum
  pkg/pureutils/pure.go
  tests/basic/pure_test.go
  vendor/github.com/devans10/pugo/flasharray/LICENSE
  vendor/github.com/devans10/pugo/flasharray/alert.go
  vendor/github.com/devans10/pugo/flasharray/alertType.go
  vendor/github.com/devans10/pugo/flasharray/array.go
  vendor/github.com/devans10/pugo/flasharray/arrayTypes.go
  vendor/github.com/devans10/pugo/flasharray/cert.go
  vendor/github.com/devans10/pugo/flasharray/certTypes.go
  vendor/github.com/devans10/pugo/flasharray/dirsrv.go
  vendor/github.com/devans10/pugo/flasharray/dirsrvTypes.go
  vendor/github.com/devans10/pugo/flasharray/flasharray.go
  vendor/github.com/devans10/pugo/flasharray/hardware.go
  vendor/github.com/devans10/pugo/flasharray/hardwareTypes.go
  vendor/github.com/devans10/pugo/flasharray/hgroup.go
  vendor/github.com/devans10/pugo/flasharray/hgroupTypes.go
  vendor/github.com/devans10/pugo/flasharray/host.go
  vendor/github.com/devans10/pugo/flasharray/hostTypes.go
  vendor/github.com/devans10/pugo/flasharray/message.go
  vendor/github.com/devans10/pugo/flasharray/messageType.go
  vendor/github.com/devans10/pugo/flasharray/network.go
  vendor/github.com/devans10/pugo/flasharray/networkTypes.go
  vendor/github.com/devans10/pugo/flasharray/offload.go
  vendor/github.com/devans10/pugo/flasharray/offloadTypes.go
  vendor/github.com/devans10/pugo/flasharray/pgroup.go
  vendor/github.com/devans10/pugo/flasharray/pgroupTypes.go
  vendor/github.com/devans10/pugo/flasharray/pod.go
  vendor/github.com/devans10/pugo/flasharray/podTypes.go
  vendor/github.com/devans10/pugo/flasharray/smtp.go
  vendor/github.com/devans10/pugo/flasharray/smtpTypes.go
  vendor/github.com/devans10/pugo/flasharray/snmp.go
  vendor/github.com/devans10/pugo/flasharray/snmpTypes.go
  vendor/github.com/devans10/pugo/flasharray/user.go
  vendor/github.com/devans10/pugo/flasharray/userTypes.go
  vendor/github.com/devans10/pugo/flasharray/vgroup.go
  vendor/github.com/devans10/pugo/flasharray/vgroupTypes.go
  vendor/github.com/devans10/pugo/flasharray/volume.go
  vendor/github.com/devans10/pugo/flasharray/volumeTypes.go
  vendor/modules.txt
Labels: ready-for-review

#1860 Testcase fix
  drivers/pds/api/backupTarget.go
  drivers/pds/lib/utils.go
  drivers/pds/parameters/pds_default_parameters.json
  drivers/pds/pdsbackup/backup_utils.go
  drivers/pds/targetcluster/targetcluster.go
  tests/pds/pds_backup_test.go
  tests/pds/pds_common.go
  tests/pds/pds_custom_scripts_test.go
  tests/pds/pds_resiliency_test.go
  tests/pds/pds_restore_negative_test.go
  tests/pds/pds_restore_test.go
Labels: ready-for-review

#1930 Schedule applications in a new namespace in every Px-Backup test
  drivers/scheduler/k8s/k8s.go
  tests/backup/backup_helper.go
  tests/common.go
Labels: framework, ready-for-review, Px-Backup
