Repository portworx/torpedo, pull requests merged in 2023-08, with the labels that each got.

#1573 Add test to update io_profile in longevity
  tests/basic/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review

#1605 PTX-19417 Updating libopenstorage/operator vendor to get the latest changes for the ValidateStorageCluster()
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/api.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/doc.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/errors.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/service.go
  vendor/github.com/aws/aws-sdk-go/service/autoscaling/waiters.go
  vendor/github.com/aws/aws-sdk-go/service/opsworks/api.go
  vendor/github.com/aws/aws-sdk-go/service/opsworks/doc.go
  vendor/github.com/aws/aws-sdk-go/service/opsworks/errors.go
  vendor/github.com/aws/aws-sdk-go/service/opsworks/service.go
  vendor/github.com/aws/aws-sdk-go/service/opsworks/waiters.go
  vendor/github.com/codegangsta/inject/.gitignore
  vendor/github.com/codegangsta/inject/LICENSE
  vendor/github.com/codegangsta/inject/README.md
  vendor/github.com/codegangsta/inject/inject.go
  vendor/github.com/codegangsta/inject/update_readme.sh
  vendor/github.com/codeskyblue/go-sh/LICENSE
  vendor/github.com/codeskyblue/go-sh/OLD_README.md
  vendor/github.com/codeskyblue/go-sh/README.md
  vendor/github.com/codeskyblue/go-sh/pipe.go
  vendor/github.com/codeskyblue/go-sh/sh.go
  vendor/github.com/codeskyblue/go-sh/test.go
  vendor/github.com/codeskyblue/go-sh/wercker.yml
  vendor/github.com/libopenstorage/cloudops/aws/README.md
  vendor/github.com/libopenstorage/cloudops/aws/aws.go
  vendor/github.com/libopenstorage/cloudops/pkg/exec/bin.go
  vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/csi_generator.go
  vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/util.go
  vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/storagecluster.go
  vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/storagenode.go
  vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/zz_generated.deepcopy.go
  vendor/github.com/libopenstorage/operator/pkg/apis/portworx/v1/portworxdiag.go
  vendor/github.com/libopenstorage/operator/pkg/mock/openstoragesdk.mock.go
  vendor/github.com/libopenstorage/operator/pkg/mock/sdkserver.go
  vendor/github.com/libopenstorage/operator/pkg/preflight/aws.go
  vendor/github.com/libopenstorage/operator/pkg/preflight/gce.go
  vendor/github.com/libopenstorage/operator/pkg/preflight/preflight.go
  vendor/github.com/libopenstorage/operator/pkg/preflight/utils.go
  vendor/github.com/libopenstorage/operator/pkg/util/k8s/pod.go
  vendor/github.com/libopenstorage/operator/pkg/util/test/util.go
  vendor/modules.txt
Labels: ready-for-review

#1607 [PA-1523] Fix ManualAndScheduleBackupUsingNamespaceLabel
  tests/backup/backup_namespace_labelled_test.go
Labels: bug, ready-for-review

#1600 PA-1484: Change `IsS3BucketEmpty()` to `IsBackupLocationEmpty()` to support nfs
  tests/backup/backup_restore_basic_test.go
Labels: bug, ready-for-review, Px-Backup

#1602 Added Rancher Test case: NamespaceMoveFromProjectToProjectToNoProjectWhileRestore
  drivers/scheduler/rke/rke.go
  tests/backup/backup_basic_test.go
  tests/backup/backup_helper.go
  tests/backup/backup_rancher_test.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#1614 PTX-19576 Updating libopenstorage/operator vendor
  go.mod
  go.sum
  vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/csi_generator.go
  vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/util.go
  vendor/github.com/libopenstorage/operator/pkg/util/test/util.go
  vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go
  vendor/github.com/portworx/sched-ops/k8s/core/pods.go
  vendor/modules.txt
Labels: ready-for-review

#1603 Adding add storage test case for longevity
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/k8s/specs/elasticsearch-rally/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/elasticsearch/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/elk-stack/es-exporter.yaml
  drivers/scheduler/k8s/specs/elk-stack/esread.yaml
  drivers/scheduler/k8s/specs/elk-stack/logging-app.yaml
  drivers/scheduler/k8s/specs/elk-stack/logstash-app.yaml
  drivers/scheduler/k8s/specs/elk-stack/px-elastic-app.yaml
  drivers/scheduler/k8s/specs/elk-stack/px-elk-sc.yaml
  drivers/scheduler/k8s/specs/elk-stack/px-kibana-app.yaml
  drivers/scheduler/k8s/specs/elk-stack/servicemonitor.yaml
  drivers/scheduler/k8s/specs/fio-aggr/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/fio-cloudsnap/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/fio-localsnap/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/fio/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/kafka-stack/pure/pure-storage-class.yaml
  drivers/scheduler/k8s/specs/kafka-stack/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/mongodb/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/nginx-shared/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-storage.yaml
  drivers/scheduler/k8s/specs/nginx/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/pgbench-io-portion/px-pgbench-storage.yaml
  drivers/scheduler/k8s/specs/pgbench/pxd/pgbench-px-storage-class.yaml
  drivers/scheduler/k8s/specs/sysbench-heavyload/pxd/storage-class.yaml
  drivers/scheduler/k8s/specs/sysbench-st/px-sysbench-app.yml
  drivers/scheduler/k8s/specs/sysbench-st/px-sysbench-storage.yml
  drivers/scheduler/k8s/specs/sysbench-st/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/sysbench/pxd/storage-class.yaml
  drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml
  drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml
  drivers/scheduler/k8s/specs/vdbench-v4-fstrim/vd-sharedv4-st.yaml
  drivers/scheduler/openshift/openshift.go
  drivers/scheduler/scheduler.go
  tests/basic/longevity_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-for-review

#1615 PA-1500 : Add bkp status check in `CreateRestore()`
  tests/backup/backup_helper.go
Labels: bug, ready-for-review, Px-Backup

#1608 Adding new RKE test case: MultipleProjectMultipleNamespacesBackupAndRestore
  drivers/scheduler/rke/rke.go
  tests/backup/backup_rancher_test.go
Labels: ready-for-review, Px-Backup

#1611 Enabled `ibm` as `CLUSTER_PROVIDER`
  deployments/deploy-pxb-cloud.sh
  drivers/drivers.go
  tests/backup/backup_basic_test.go
  tests/backup/backup_helper.go
  tests/common.go
Labels: framework, ready-for-review, Px-Backup

#1623 Corrected testcase :NamespaceMoveFromProjectToProjectToNoProjectWhileRestore
  tests/backup/backup_rancher_test.go
Labels: ready-for-review

#1625 Adding ocp node recycle test
  drivers/node/node.go
  drivers/node/vsphere/vsphere.go
  drivers/scheduler/openshift/openshift.go
  tests/basic/longevity_test.go
  tests/basic/ocp_node_recycle_test.go
  tests/testTriggers.go
Labels: ready-for-review

#1631 Corrected test case name
  tests/backup/backup_rancher_test.go
Labels: ready-for-review

#1633 [PA-1597] Fix test names in StartTorpedoTest
  tests/backup/backup_locked_bucket_test.go
  tests/backup/backup_restore_basic_test.go
  tests/backup/backup_test.go
  tests/backup/backup_upgrade_test.go
Labels: ready-for-review, Px-Backup
