Repository portworx/torpedo, pull requests merged in 2024-04, with the labels that each got.

#2279 PB-6466: Remove non-existing test from `backup_test_labels.go`
  tests/backup/backup_test_labels.go
Labels: ready-for-review, Px-Backup

#2263 Charmed k8s : Disable the log collection in EndPxBackupTorpedoTest untill we find a way to ssh from juju
  tests/common.go
Labels: ready-for-review, Px-Backup

#2229 [PTX-22947] Print Volume inspect after volume operations in longevity
  tests/common.go
  tests/testTriggers.go
Labels: in-progress

#2285 PB-6468: Change code to take VM backups if kubevirt in `BasicBackupCreation`
  drivers/scheduler/k8s/specs/kubevirt-cirros-cd-with-pvc/vm-cirros.yaml
  tests/backup/backup_sanity_test.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#2273 TestCase Automation : Backup and restore of namespaces with multiple provisioners using csi (vsc mapping) and kdmp
  drivers/scheduler/k8s/specs/postgres-cephfs-csi/ocp/cephfs-csi-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-cephfs-csi/storage.yaml
  drivers/scheduler/k8s/specs/postgres-rbd-csi/ocp/rbd-csi-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-rbd-csi/storage.yaml
  tests/backup/backup_multiple_provisioner_test.go
  tests/backup/backup_test_labels.go
Labels: ready-for-review, Px-Backup

#2293 Added Kubevirt related steps in upgrade test
  tests/backup/backup_kubevirt_test.go
  tests/backup/backup_upgrade_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup, testing-in-progress

#2251 Adding verification for Pool Resize and Pool rebalance
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  tests/basic/autopilot_test.go
Labels: ready-for-review

#2296 PB-6550: Minor fix in `LockedBucketResizeVolumeOnScheduleBackup` test
  tests/backup/backup_locked_bucket_test.go
Labels: ready-to-merge, Px-Backup

#2301 Fixed the number of retain count to avoid restore failure
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup

#2244 [PTX-23000] Pool expand check for DMTHIN
  tests/basic/storage_pool_test.go
  tests/common.go
Labels: ready-for-review, testing-in-progress

#2286 [PTX-22351] Adding OKE Schedular upgrade test
  Dockerfile
  deployments/deploy-ssh.sh
  drivers/scheduler/oke/oke.go
  drivers/volume/portworx/schedops/oke-schedops.go
  tests/basic/px_cluster_migration_test.go
  tests/basic/upgrade_cluster_test.go
  tests/common.go
Labels: ready-for-review

#2309 Stabilise existing RBAC tests
  drivers/unifiedPlatform/automationModels/apiTypes.go
  drivers/unifiedPlatform/automationModels/common.go
  drivers/unifiedPlatform/automationModels/iamRoleBindings.go
  drivers/unifiedPlatform/automationModels/serviceAccount.go
  drivers/unifiedPlatform/platform/backend/v1/api/common.go
  drivers/unifiedPlatform/platform/backend/v1/api/iamRoleBindings.go
  drivers/unifiedPlatform/platform/backend/v1/api/serviceAccount.go
  drivers/unifiedPlatform/platform/backend/v1/grpc/iamRoleBindings.go
  drivers/unifiedPlatform/platform/backend/v1/grpc/serviceAccount.go
  drivers/unifiedPlatform/platform/platform.go
  drivers/unifiedPlatform/platformLibs/iamRoleBindings.go
  drivers/unifiedPlatform/platformLibs/serviceAccounts.go
  drivers/unifiedPlatform/stworkflows/workflowNamespace.go
  drivers/unifiedPlatform/stworkflows/workflowServiceAccount.go
  drivers/unifiedPlatform/utils/api_helper.go
  tests/unifiedPlatform/platform/platform_basic_test.go
  tests/unifiedPlatform/platform/platform_test.go
  tests/unifiedPlatform/platform/platform_test_dummy.go
Labels: ready-for-review

#2315 Fixed the kubevirt tests for NFS backup location
  drivers/scheduler/k8s/k8s.go
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup

#2302 [PTX-21638] Fix ValidateCreateVolume
  drivers/volume/portworx/portworx.go
Labels: ready-for-review

#2318 Fix pagination issue is automation
  drivers/unifiedPlatform/automationModels/backup.go
  drivers/unifiedPlatform/automationModels/backupConfig.go
  drivers/unifiedPlatform/automationModels/namespaces.go
  drivers/unifiedPlatform/automationModels/project.go
  drivers/unifiedPlatform/automationModels/targetCluster.go
  drivers/unifiedPlatform/pds/backend/v1/api/backup.go
  drivers/unifiedPlatform/pds/backend/v1/api/backupConfig.go
  drivers/unifiedPlatform/pdsLibs/backup.go
  drivers/unifiedPlatform/pdsLibs/backupConfig.go
  drivers/unifiedPlatform/pdsLibs/common.go
  drivers/unifiedPlatform/pdsLibs/validateBackupRestore.go
  drivers/unifiedPlatform/platform/backend/v1/api/namespace.go
  drivers/unifiedPlatform/platform/backend/v1/api/project.go
  drivers/unifiedPlatform/platform/backend/v1/api/targetCluster.go
  drivers/unifiedPlatform/platformLibs/common.go
  drivers/unifiedPlatform/platformLibs/namespace.go
  drivers/unifiedPlatform/platformLibs/project.go
  drivers/unifiedPlatform/platformLibs/targetCluster.go
  drivers/unifiedPlatform/stworkflows/workflowPDSBackup.go
  drivers/unifiedPlatform/stworkflows/workflowPDSBackupConfig.go
Labels: ready-for-review

#2319 Refactor PDS and platform workflows to different folders
  drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go
  drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go
  drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go
  drivers/unifiedPlatform/stworkflows/pds/workflowResiliency.go
  drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go
  drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go
  drivers/unifiedPlatform/stworkflows/platform/workflowBackupLocation.go
  drivers/unifiedPlatform/stworkflows/platform/workflowCloudCredentials.go
  drivers/unifiedPlatform/stworkflows/platform/workflowNamespace.go
  drivers/unifiedPlatform/stworkflows/platform/workflowPlatform.go
  drivers/unifiedPlatform/stworkflows/platform/workflowProject.go
  drivers/unifiedPlatform/stworkflows/platform/workflowServiceAccount.go
  drivers/unifiedPlatform/stworkflows/platform/workflowTargetCluster.go
  drivers/unifiedPlatform/stworkflows/platform/workflowTenant.go
  tests/unifiedPlatform/common.go
  tests/unifiedPlatform/pds2/pds_basic_test.go
  tests/unifiedPlatform/pds2/pds_dataservice_test.go
  tests/unifiedPlatform/pds2/pds_resiliency_test.go
  tests/unifiedPlatform/pds2/pds_restore_test.go
  tests/unifiedPlatform/platform/platform_test.go
  tests/unifiedPlatform/platform/platform_test_dummy.go
Labels: ready-for-review

#2324 Add KubeVirtPvcAndPoolExpandWithAutopilot
  tests/basic/kubevirt_test.go
Labels: ready-for-review

#2328 [PTX-23277] Fix ValidateCreateVolume
  drivers/volume/portworx/portworx.go
Labels: ready-for-review, testing-in-progress

#2307 [PTX-23237]Moving delete node to schedulers
  drivers/node/node.go
  drivers/scheduler/aks/aks.go
  drivers/scheduler/anthos/anthos.go
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/eks/eks.go
  drivers/scheduler/gke/gke.go
  drivers/scheduler/iks/iks.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/oke/oke.go
  drivers/scheduler/openshift/openshift.go
  drivers/scheduler/rke/rke.go
  drivers/scheduler/scheduler.go
  tests/basic/asg_test.go
  tests/basic/ocp_node_recycle_test.go
  tests/basic/sharedv4_multivol_test.go
  tests/basic/upgrade_cluster_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-for-review

#2344 PDS 2.0 testcase refactor - PerformSimultaneousBackupRestoreForMultipleDeployments
  tests/unifiedPlatform/pds2/pds_restore_test.go
Labels: ready-for-review

#2228 [PTX-22914] Enhance UpgradeLongevity
  deployments/deploy-ssh.sh
  pkg/stats/stats.go
  tests/basic/license_test.go
  tests/basic/upgrade_test.go
  tests/common.go
  tests/longevity/longevity_helper.go
  tests/longevity/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2359 [PTX-23388] Add GinkgoRecover In UpgradeLongevity
  tests/longevity/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2353 Stabilise Basic Restore Tests
  drivers/unifiedPlatform/pds/backend/v1/api/backup.go
  drivers/unifiedPlatform/pds/backend/v1/api/backupConfig.go
  drivers/unifiedPlatform/pds/backend/v1/api/restore.go
  drivers/unifiedPlatform/pdsLibs/backupConfig.go
  drivers/unifiedPlatform/pdsLibs/restore.go
  drivers/unifiedPlatform/pdsLibs/validateBackupRestore.go
  drivers/unifiedPlatform/platform/backend/v1/api/backupLocation.go
  drivers/unifiedPlatform/platform/backend/v1/api/cloudCredentials.go
  drivers/unifiedPlatform/stworkflows/common.go
  drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go
  drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go
  drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go
  tests/unifiedPlatform/pds2/pds_basic_test.go
  tests/unifiedPlatform/pds2/pds_dataservice_test.go
  tests/unifiedPlatform/pds2/pds_dummy_test.go
  tests/unifiedPlatform/pds2/pds_restore_test.go
Labels: ready-for-review

#2329 --provisioning-commit-labels should honor while resizing volume
  tests/basic/volume_ops_test.go
Labels: ready-to-merge

#2367 Add cleanup validation for namespace workflow
  drivers/unifiedPlatform/automationModels/namespaces.go
  drivers/unifiedPlatform/platform/backend/v1/api/namespace.go
  drivers/unifiedPlatform/platform/backend/v1/grpc/namespace.go
  drivers/unifiedPlatform/platform/platform.go
  drivers/unifiedPlatform/platformLibs/namespace.go
  drivers/unifiedPlatform/stworkflows/platform/workflowNamespace.go
  drivers/utilities/k8sUtils.go
  drivers/utilities/utilities.go
  tests/unifiedPlatform/pds2/pds_basic_test.go
  tests/unifiedPlatform/pds2/pds_restore_test.go
  tests/unifiedPlatform/platform/platform_test.go
  tests/unifiedPlatform/platform/platform_test_dummy.go
Labels: ready-for-review

#2368 Add cleanup validation for project workflow
  drivers/unifiedPlatform/platform/backend/v1/api/project.go
  drivers/unifiedPlatform/stworkflows/platform/workflowProject.go
  tests/unifiedPlatform/pds2/pds_restore_test.go
Labels: ready-for-review

#2336 Adding px-bkp KubevirtVMMigrationTest
  drivers/scheduler/k8s/specs/kubevirt-cirros-live-migration/vm-cirros.yaml
  tests/backup/backup_kubevirt_test.go
  tests/backup/backup_test_labels.go
  tests/backup_helper.go
  tests/kubevirt_helper.go
Labels: new-test, ready-for-review, Px-Backup

#2349 Removed steps from long running kubevirt tests
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup

#2380 PTX-23460 Vendor update of libopenstorage/operator package for Telemetry output check when PX in debug mod fix
  go.mod
  go.sum
  vendor/github.com/libopenstorage/operator/pkg/util/test/util.go
  vendor/modules.txt
Labels: ready-for-review

#2366 [PTX-23400] Fix VerifyPoolDeleteInvalidPoolID
  tests/basic/storage_pool_test.go
Labels: ready-for-review

#2386 Removed deletion of app after deleting the VM
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup

#2389 Added log.InfoD for CreateBackupByNamespacesWithoutCheck
  tests/backup_helper.go
Labels: ready-for-review

#2390 Add cleanup validation for backup workflow
  drivers/unifiedPlatform/pds/backend/v1/api/backupConfig.go
  drivers/unifiedPlatform/pdsLibs/backupConfig.go
  drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go
  drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go
  drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go
  tests/unifiedPlatform/pds2/pds_basic_test.go
  tests/unifiedPlatform/pds2/pds_restore_test.go
Labels: ready-for-review

#2392 Fixed VM spec deletion issue in KubevirtScheduledVMDelete
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup

#2381 Adding GetASGClusterSize and SetASGClusterSize as part of scheduler d…
  deployments/deploy-ssh.sh
  drivers/scheduler/aks/aks.go
  drivers/scheduler/anthos/anthos.go
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/eks/eks.go
  drivers/scheduler/iks/iks.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/openshift/openshift.go
  drivers/scheduler/rke/rke.go
  drivers/scheduler/scheduler.go
  tests/basic/asg_test.go
  tests/basic/customer_issues_test.go
  tests/basic/storage_pool_test.go
  tests/common.go
Labels: ready-for-review

#2399 [PTX-23522] Fix initiatePoolExpansion
  tests/testTriggers.go
Labels: ready-for-review

#2352 [PTX-20557] Added test scenarios for testing sources option in ha-update
  tests/basic/volume_ops_test.go
Labels: ready-for-review

#2402 Added a sleep for validating px-backup pods to be ready
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup

#2396 Added stork controller configmap verification after updating stork admin ns
  tests/backup/backup_stork_test.go
  tests/backup_helper.go
Labels: ready-for-review

#2416 Run all tests even if some tests are failed
  tests/unifiedPlatform/common.go
  tests/unifiedPlatform/pds2/pds_basic_test.go
  tests/unifiedPlatform/pds2/pds_restore_test.go
  tests/unifiedPlatform/platform/platform_basic_test.go
  tests/unifiedPlatform/platform/platform_test.go
Labels: ready-for-review

#2383 Kubevirt Torpedo improvements
  drivers/scheduler/k8s/specs/kubevirt-debian-fio-low-ha/boot-pvc.yaml
  drivers/scheduler/k8s/specs/kubevirt-debian-fio-low-ha/pxd/sc.yaml
  drivers/scheduler/k8s/specs/kubevirt-debian-fio-low-ha/vm.yaml
  drivers/scheduler/k8s/specs/kubevirt-debian-fio-minimal/boot-pvc.yaml
  drivers/scheduler/k8s/specs/kubevirt-debian-fio-minimal/pxd/sc.yaml
  drivers/scheduler/k8s/specs/kubevirt-debian-fio-minimal/vm.yaml
  drivers/scheduler/k8s/specs/kubevirt-debian-template/boot-pvc.yaml
  tests/basic/kubevirt_test.go
  tests/kubevirt_helper.go
Labels: testing-in-progress

#2423 Update project admin flow in RBAC test
  tests/unifiedPlatform/platform/platform_test.go
Labels: ready-for-review

#2430 Fix restore NS name
  tests/backup/backup_share_test.go
Labels: bug, ready-for-review, Px-Backup

#2361 [TC Automation] PTX-21440 Add test case VolAttachFAPxRestart
  deployments/deploy-ssh.sh
  pkg/pureutils/pure_types.go
  pkg/pureutils/purefa.go
  tests/basic/pure_test.go
  tests/common.go
Labels: ready-for-review

#2406 Adding cloud create and s3 bucket deletion function for cloudsnaps
  drivers/scheduler/k8s/k8s.go
  tests/backup/backup_upgrade_test.go
  tests/basic/customer_issues_test.go
  tests/basic/kubevirt_test.go
  tests/basic/node_decommission_test.go
  tests/basic/upgrade_cluster_test.go
  tests/basic/volume_ops_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-to-merge

#2393 Adding ZRS disk spec for aks
  drivers/scheduler/k8s/specs/postgres-azure-disk-zone/azure/azure-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-azure-disk-zone/postgres-azure-zrsdisk-app.yaml
  drivers/scheduler/k8s/specs/postgres-azure-disk-zone/storage.yaml
Labels: ready-for-review, Px-Backup

#2418 Added method for creating volume snapshot class with the given provisioner
  apiServer/taas/apiserver.go
  apiServer/taas/utils/k8sutils.go
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
Labels: ready-for-review

#2282 PB-5946: Added logic for PVC cleanup validation
  tests/backup/backup_basic_test.go
  tests/backup_helper.go
Labels: Px-Backup

#2434 Added pxbackup version check to verify api call
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup
