Repository portworx/torpedo, pull requests merged in 2024-05, with the labels that each got.

#2443 Anthos upgrade is failing in reconcile preflight check
  drivers/scheduler/anthos/anthos.go
Labels: ready-for-review

#2459 Fixing the user name length because it is used in namespace creation …
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2471 Fix retry for GetPxBackupVersionString
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup

#2474 Fix pvc cleanup issue
  tests/backup/backup_basic_test.go
Labels: Px-Backup

#2473 Adding test to recycle all storage driver nodes and validate drive set in cloud platforms
  drivers/node/ssh/ssh.go
  drivers/volume/portworx/schedops/k8s-schedops.go
  tests/basic/asg_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2478 Temporary removeal of pvc cleanup validation
  tests/backup/backup_basic_test.go
Labels: ready-for-review, Px-Backup

#2479 Added retry method : WaitForBackupLocationAddition for backup location validation
  tests/backup/backup_portworx_test.go
  tests/backup_helper.go
Labels: in-progress

#2480 Removed data validation error check due to PB-6271 , Enabled deletebackups true for cluster delete in cleanup
  tests/backup_helper.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#2465 [PTX-23856] Increase Timeout In ValidateStorageCluster
  drivers/volume/portworx/portworx.go
  tests/basic/upgrade_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2477 PB-6917: Add `CUSTOM_REGISTRY` and `CUSTOM_REPO` to support custom registry deployment
  deployments/deploy-pxb-cloud.sh
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2491 Run torpedo as a pod in anthos user cluster
  deployments/deploy-ssh.sh
Labels: ready-for-review

#2489 PTX-24028 Vendor latest libopenstorage/operator package
  go.mod
  go.sum
  vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/util.go
  vendor/github.com/libopenstorage/operator/pkg/constants/metadata.go
  vendor/github.com/libopenstorage/operator/pkg/util/k8s/k8s.go
  vendor/github.com/libopenstorage/operator/pkg/util/test/util.go
  vendor/modules.txt
Labels: ready-for-review

#2506 Vendor latest changes from px-backup-api for 2.7.1
  go.mod
  go.sum
  vendor/github.com/libopenstorage/openstorage/api/spec/spec_handler.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.pb.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.proto
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.swagger.json
  vendor/modules.txt
Labels: ready-for-review, Px-Backup

#2436 Power-off and power-on all worker nodes
  drivers/node/vsphere/vsphere.go
  tests/longevity/longevity_helper.go
  tests/longevity/longevity_test.go
  tests/testTriggers.go
Labels: ready-to-merge, ready-for-review

#2512 [PTX-24172] Fix validateAutoFsTrim
  tests/testTriggers.go
Labels: ready-for-review

#2408 Detach clouddrives while IO inprogress and verify pool can be back after maintenance cycle
  drivers/node/node.go
  drivers/node/vsphere/vsphere.go
  drivers/volume/portworx/portworx.go
  tests/longevity/longevity_helper.go
  tests/longevity/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2509 [PTX-24076] Add Ginkgo Support To Deployment Script
  Dockerfile
  deployments/deploy-ssh.sh
Labels: ready-for-review

#2524 [PTX-23863] Fix SetupProxyServer
  tests/basic/storage_pool_test.go
  tests/common.go
Labels: ready-for-review

#2444 Adding cloudsnap delete event to longevity
  drivers/volume/common.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  tests/longevity/longevity_helper.go
  tests/longevity/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2527 Adding ability to run Px-Backup tests with Px-Security enabled
  drivers/volume/portworx/portworx.go
  drivers/volume/portworx/schedops/dcos-schedops.go
  drivers/volume/portworx/schedops/k8s-schedops.go
  drivers/volume/portworx/schedops/schedops.go
  tests/backup/backup_basic_test.go
Labels: framework, ready-for-review, Px-Backup

#2516 Fixing OCP zones
  drivers/node/vsphere/vsphere.go
  drivers/scheduler/openshift/openshift.go
  drivers/volume/portworx/portworx.go
  tests/basic/storage_pool_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-for-review

#2533 Removed aks node driver
  deployments/deploy-pxb-cloud.sh
Labels: Px-Backup

#2501 PTX-24002 Create Volume clone for FADA volume and verify new volume is created in the backend
  tests/basic/pure_test.go
Labels: ready-for-review

#2521 Added mysql & postgres spec with restricted PSA
  drivers/scheduler/k8s/specs/mysql-backup-psa-restricted/px-mysql-app.yaml
  drivers/scheduler/k8s/specs/mysql-backup-psa-restricted/px-mysql-storage.yaml
  drivers/scheduler/k8s/specs/mysql-backup-psa-restricted/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-backup-psa-restricted/px-postgres-app.yaml
  drivers/scheduler/k8s/specs/postgres-backup-psa-restricted/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-backup-psa-restricted/storage.yaml
Labels: ready-for-review

#2552 Waiting for atleast 2 mongo pods to come up after scaling down to 0 and scaling backup to 3 again
  tests/backup/backup_resiliency_test.go
  tests/backup_helper.go
Labels: ready-for-review
