Repository portworx/torpedo, pull requests merged in 2024-08, with the labels that each got.

#2712 PB-7687: Change check to see if PX is healthy or not
  tests/backup/backup_upgrade_test.go
Labels: bug, ready-for-review, Px-Backup

#2711 Removing non-mandatory parameter check for azure cloud credential
  tests/common.go
Labels: ready-for-review

#2717 PB-7691: Add support for Azure immutable container creation
  deployments/deploy-pxb-cloud.sh
  deployments/deploy-ssh.sh
  tests/common.go
Labels: ready-for-review, Px-Backup, Lib

#2719 PB-7768: Add function to dump test data in configmap
  tests/backup/backup_sanity_test.go
  tests/common.go
Labels: ready-for-review, Px-Backup, Lib

#2718 New TC: Aks cloud account with mandatory and non mandatory fields
  tests/backup/backup_azure_credential_test.go
  tests/backup/backup_basic_test.go
  tests/backup/backup_test_labels.go
  tests/common.go
Labels: ready-for-review

#2724 [PTX-25417] Resolve Panic Due to errChan Closure in Longevity
  drivers/scheduler/k8s/specs/elasticsearch/px-elasticdata-app.yaml
  tests/testTriggers.go
Labels: ready-for-review

#2716 [PTX-25477] Update deploy-ssh.sh to Overwrite Existing Kubernetes Res…
  deployments/deploy-ssh.sh
  drivers/node/node_registry.go
  tests/testTriggers.go
Labels: ready-for-review

#2723 PTX-25468 Add MaxSurge for AKS upgrade method
  deployments/deploy-ssh.sh
  drivers/scheduler/aks/aks.go
Labels: ready-for-review

#2720 Vendor latest px-backup cluster share api
  go.mod
  go.sum
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.pb.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.pb.gw.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.proto
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.swagger.json
  vendor/modules.txt
Labels: Px-Backup, Lib

#2726 Added new Azure testcase:TC2 Automation: Verify the error handling for Azure immutability with Azure creds having only the mandatory fields
  tests/backup/backup_azure_credential_test.go
  tests/backup/backup_test_labels.go
Labels: ready-for-review

#2703 Added helper function for adding multiple clusters to Px-Backup
  tests/common.go
Labels: ready-for-review

#2735 Corrected the testcase id
  tests/backup/backup_azure_credential_test.go
Labels: ready-for-review

#2709 PTX-25073: Validate volume quorum for cluster and PX upgrade
  drivers/scheduler/openshift/openshift.go
  tests/basic/upgrade_cluster_test.go
  tests/basic/upgrade_test.go
  tests/common.go
Labels: ready-for-review

#2732 PB-7692 & PB-7802: Add wrapper functions and update existing tests to run with Azure
  tests/backup/backup_basic_test.go
  tests/backup/backup_delete_test.go
  tests/backup/backup_dr_test.go
  tests/backup/backup_kdmp_test.go
  tests/backup/backup_kubevirt_test.go
  tests/backup/backup_locked_bucket_test.go
  tests/backup/backup_multiple_provisioner_test.go
  tests/backup/backup_namespace_labelled_test.go
  tests/backup/backup_nfs_test.go
  tests/backup/backup_partial_test.go
  tests/backup/backup_portworx_test.go
  tests/backup/backup_psa_test.go
  tests/backup/backup_rbac_test.go
  tests/backup/backup_restore_basic_test.go
  tests/backup/backup_sanity_test.go
  tests/backup/backup_share_test.go
  tests/backup/backup_sse_test.go
  tests/backup/backup_stork_test.go
  tests/backup/backup_upgrade_test.go
  tests/backuptestTriggers.go
  tests/common.go
Labels: ready-for-review, Px-Backup, Lib

#2744 PB-7894: Vendor in latest changes for `GetRetentionTimestamp()`
  go.mod
  go.sum
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.pb.go
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.proto
  vendor/github.com/portworx/px-backup-api/pkg/apis/v1/api.swagger.json
  vendor/modules.txt
Labels: ready-for-review, Px-Backup

#2740 Adding new test case for Azure cred change with PXB upgrade
  tests/backup/backup_test_labels.go
  tests/backup/backup_upgrade_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2731 Increase timeout for validateCRCleanup and added go routine for backup delete
  tests/backup/backup_delete_test.go
  tests/backup/backup_upgrade_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup
