Repository portworx/torpedo, pull requests merged in 2024-07, with the labels that each got.

#2638 Adding a new test case PartialBackupWithLowerStorkVersion
  tests/backup/backup_partial_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2642 label for partial backup tests
  tests/backup/backup_partial_test.go
  tests/backup/backup_test_labels.go
Labels: ready-for-review, Px-Backup

#2643 Adding custom bucket for PartialBackupSuccessWithAzureEndpoint
  tests/backup/backup_partial_test.go
Labels: Px-Backup

#2609 PB-7119: PSA automation for taking backup in lower privilege to higher privilege
  tests/backup/backup_psa_test.go
  tests/backup/backup_test_labels.go
  tests/backup_helper.go
Labels: ready-for-review

#2651 Adding more logging info and fixing re-init of originalAppList
  tests/backup/backup_psa_test.go
Labels: ready-for-review, Px-Backup

#2645 Adding pool delete event for longevity
  drivers/scheduler/k8s/k8s.go
  drivers/volume/portworx/portworx.go
  tests/basic/node_decommission_test.go
  tests/basic/pure_test.go
  tests/basic/storage_pool_test.go
  tests/common.go
  tests/longevity/longevity_helper.go
  tests/longevity/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2641 Adding PSA TC : PSALowerPrivilegeToHigherPrivilegeWithProjectMapping
  tests/backup/backup_psa_test.go
  tests/backup/backup_test_labels.go
Labels: ready-for-review

#2640 Modified rancher testcases to get cluster name
  deployments/deploy-ssh-taas.sh
  deployments/deploy-ssh.sh
  drivers/scheduler/rke/rke.go
  tests/backup/backup_basic_test.go
  tests/backup/backup_psa_test.go
  tests/backup/backup_rancher_test.go
Labels: ready-for-review

#2653 PB-7471: fix testcase PsaTakeBackupInLowerPrivilegeRestoreInHigherPrivilege
  tests/backup/backup_psa_test.go
Labels: ready-for-review

#2656 Refactoring app specs for partial backup feature
  drivers/node/ssh/ssh.go
  drivers/scheduler/k8s/specs/mysql-backup-data/px-mysql-app.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-aks/mysql-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-aks/mysql-pvc.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-aks/pg-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-aks/pg-pvc.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-iks/mysql-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-iks/mysql-pvc.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-iks/pg-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-iks/pg-pvc.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-ocp/mysql-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-ocp/mysql-pvc.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-ocp/pg-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-ocp/pg-pvc.yaml
  drivers/scheduler/k8s/specs/pxb-multipleapp-multivol/mutiple_app_multivol.yaml
  tests/backup/backup_partial_test.go
  tests/backup_helper.go
  tests/common.go
Labels: Px-Backup

#2661 Adding invalid provisioner for CreateInvalidVolumeSnapshotClass(
  tests/backup_helper.go
Labels: Px-Backup

#2664 Increasing the wait time after Px STC update
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-iks/pg-deployment.yaml
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2652 PTX-24004 Restart the PX after recreating PX-pure secret and make sure it is up
  tests/basic/pure_test.go
Labels: ready-for-review

#2646 PTX-24005 Restart the px cluster and validate FA volumes and check FA volumes in the FA Backend
  tests/basic/pure_test.go
Labels: ready-for-review

#2561 PTX-23972 Validate Cloud drives created are spread accross multiple FA's listed in pure.json file
  tests/basic/pure_test.go
Labels: ready-for-review

#2677 Added mysql specs for ceph and rbd
  drivers/scheduler/k8s/specs/mysql-ocp-cephfs/mysql-app.yaml
  drivers/scheduler/k8s/specs/mysql-ocp-cephfs/mysql-storage.yaml
  drivers/scheduler/k8s/specs/mysql-ocp-rbd/mysql-app.yaml
  drivers/scheduler/k8s/specs/mysql-ocp-rbd/mysql-storage.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-ocp/mysql-deployment.yaml
Labels: ready-for-review, Px-Backup

#2629 PWX-37402 Automate enabling/disabling interface endpoints to test Multiple management IPs
  deployments/deploy-ssh.sh
  drivers/pure/flasharray/fa.go
  drivers/pure/flasharray/network.go
  drivers/pure/flasharray/networkInterfaces.go
  pkg/pureutils/purefa.go
  pkg/pureutils/purefa_rest2x.go
  tests/basic/basic_test.go
  tests/common.go
Labels: ready-for-review

#2647 PTX-24898 Restart the px while managment interface is down and enable interface during start of px
  tests/basic/pure_test.go
Labels: ready-for-review

#2682 Adding longevity trigger for defrag schedule
  drivers/volume/common.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  go.mod
  go.sum
  tests/longevity/longevity_helper.go
  tests/longevity/longevity_test.go
  tests/testTriggers.go
  vendor/github.com/libopenstorage/openstorage/api/api.go
  vendor/github.com/libopenstorage/openstorage/api/api.pb.go
  vendor/github.com/libopenstorage/openstorage/api/api.pb.gw.go
  vendor/github.com/libopenstorage/openstorage/api/api.proto
  vendor/github.com/libopenstorage/openstorage/api/spec/spec_handler.go
  vendor/github.com/libopenstorage/openstorage/pkg/mount/mount.go
  vendor/modules.txt
Labels: ready-for-review

#2681 Fixing the test RebootNodesWhenBackupsAreInProgress for non-px runs
  drivers/node/ssh/ssh.go
  drivers/volume/ocp/ocp.go
  tests/backup/backup_resiliency_test.go
Labels: ready-for-review, Px-Backup

#2683 Adding token for pxctl commands if security is enabled
  drivers/node/ssh/ssh.go
  drivers/volume/portworx/portworx.go
  tests/common.go
Labels: ready-for-review

#2687 Adding app spec for GKE for partial backup feature
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-gke/mysql-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-gke/mysql-pvc.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-gke/pg-deployment.yaml
  drivers/scheduler/k8s/specs/pg-mysql-multiprov-gke/pg-pvc.yaml
  tests/backup/backup_partial_test.go
  tests/backup_helper.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#2688 Fixed the TC PXBackupEndToEndBackupAndRestoreWithUpgrade
  tests/backup/backup_upgrade_test.go
  tests/backup_helper.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#2689 fixes for SSIE workflow
  drivers/scheduler/k8s/k8s.go
  drivers/volume/portworx/portworx.go
  tests/testTriggers.go
Labels: ready-for-review

#2691 Fix ScaleMongoDBWhileBackupAndRestore failure on OCP with OCS
  tests/backup/backup_resiliency_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2693 PTX-25257 Fix deleting admin security context even if cmd fails
  drivers/node/ssh/ssh.go
Labels: ready-for-review

#2700 [PTX-25287] Fix postgres-backup-multivol Spec
  drivers/scheduler/k8s/specs/postgres-backup-multivol/px-postgres-pvc.yaml
  drivers/scheduler/k8s/specs/postgres-backup-multivol/pxd/px-storage-class.yaml
Labels: testing-in-progress

#2702 Resetting the ClaimsCount after the test case KubevirtVMRestoreWithAfterChangingVMConfig completes
  tests/backup/backup_kubevirt_test.go
Labels: ready-for-review, Px-Backup
