Repository portworx/torpedo, pull requests merged in 2024-06, with the labels that each got.

#2540 PWX-37370 Automation deleting VolumeSnapshots and ensuring they are deleted successfully
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  drivers/volume/common.go
  drivers/volume/portworx/portworx.go
  drivers/volume/portworx/pure.go
  drivers/volume/volume.go
  tests/basic/pure_test.go
  tests/common.go
Labels: ready-for-review

#2514 [PTX-23995] Create base,fbda,fada pvc with iops and bandwidth storageclasss and validate volumes created in FA AND FB
  drivers/scheduler/k8s/k8s.go
  pkg/pureutils/purefa_rest2x.go
  pkg/pureutils/purefb.go
  tests/basic/pure_test.go
  tests/common.go
Labels: ready-for-review

#2534 PTX-23996 Rebooting Node while FADA Volume creation in progress ( Use Zones)
  drivers/scheduler/k8s/specs/fio-zones/fio-config-map.yaml
  drivers/scheduler/k8s/specs/fio-zones/fio.yaml
  drivers/scheduler/k8s/specs/fio-zones/px-storage-class.yaml
  tests/basic/pure_test.go
Labels: ready-for-review

#2535 Adding deleteNode method for anthos scheduler
  deployments/deploy-ssh.sh
  drivers/scheduler/anthos/anthos.go
  go.mod
  go.sum
  tests/basic/asg_test.go
  tests/common.go
  vendor/github.com/portworx/sched-ops/k8s/anthos/anthos.go
  vendor/github.com/portworx/sched-ops/k8s/anthos/machines.go
  vendor/github.com/portworx/sched-ops/k8s/core/core.go
  vendor/github.com/portworx/sched-ops/k8s/core/events.go
  vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/kubevirt.go
  vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go
  vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
  vendor/modules.txt
Labels: ready-for-review

#2499 PTX-23985 Px Volume Resize in parallel to FADA/FBDA Volume Resize
  tests/basic/pure_test.go
Labels: ready-for-review

#2541 PWX-37401 Test stopping Portworx on a node for 10 minutes, then starting it again
  tests/basic/pure_test.go
Labels: ready-for-review

#2530 changes to deploy just apps and printDisk properties
  tests/basic/asg_test.go
  tests/basic/misc_test.go
  tests/basic/upgrade_cluster_test.go
Labels: ready-for-review

#2559 Vendoring latest sched-ops changes
  go.mod
  go.sum
  vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstancemigration.go
  vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
  vendor/modules.txt
Labels: ready-for-review, Px-Backup

#2566 Adding function to modify maintenance job frequency
  tests/backup/backup_sanity_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2555 PB-7095 & PB-7096: Add libs for enabling cluster wide PSA
  tests/backup/backup_psa_test.go
  tests/backup/backup_test_labels.go
  tests/common.go
Labels: ready-for-review, Px-Backup, Lib

#2556 PB-7116: Add Method to verify the labels after adding labels to the namespace
  tests/backup_helper.go
Labels: Px-Backup

#2563 PTX-22409:Fixing cluster status validation during platform upgrades
  tests/basic/upgrade_cluster_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-for-review

#2517 Modifed helper functions for Azure Cloud [PxB 2.7.1]
  deployments/deploy-pxb-cloud.sh
  deployments/deploy-ssh.sh
  tests/common.go
Labels: ready-to-merge, Px-Backup

#2573 PTX-24254:Adding logic to validate pools for limit before expansion
  drivers/pds/lib/utils.go
  drivers/volume/common.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  pkg/units/units.go
  tests/basic/ha_update_test.go
  tests/basic/misc_test.go
  tests/basic/pool_function_test.go
  tests/basic/pure_test.go
  tests/basic/storage_pool_test.go
  tests/basic/volume_ops_test.go
  tests/common.go
  tests/longevity/longevity_helper.go
  tests/testTriggers.go
Labels: ready-for-review

#2551 Helper methods to add cluster wide PSA in Rancher
  drivers/scheduler/rke/rke.go
  tests/backup/backup_rancher_test.go
  tests/backup_helper.go
  vendor/github.com/rancher/rancher/pkg/client/generated/management/v3/zz_generated_pod_security_admission_configuration_template_defaults.go
Labels: ready-for-review

#2576 Helper method to clean specific files from S3 bucket
  tests/common.go
Labels: ready-to-merge, Px-Backup

#2577 Added a function UpdateMaintenanceCronJob
  tests/backup/backup_sanity_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2582 PTX-24281:moving repls on the node before pool deletion
  tests/basic/storage_pool_test.go
  tests/common.go
Labels: ready-for-review

#2587 Added method CreateVolumeSnapshotClassesWithParameters
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup, Lib

#2564 PTX-24429 support for realms and pods
  drivers/pure/flasharray/fa.go
  drivers/pure/flasharray/pods.go
  drivers/pure/flasharray/podsTypes.go
  drivers/pure/flasharray/realms.go
  drivers/pure/flasharray/realmsTypes.go
  pkg/pureutils/pure_types.go
  pkg/pureutils/purefa_rest2x.go
Labels: ready-for-review

#2571 PWX-37369 Automation checking for pod name in pxctl v i
  drivers/scheduler/k8s/specs/fio-fa-davol/px-storage-class.yaml
  drivers/scheduler/k8s/specs/fio-zones/px-storage-class.yaml
  drivers/scheduler/k8s/specs/nginx-fa-davol/pure/px-storage-class.yaml
  drivers/scheduler/k8s/specs/nginx-fada-deploy/pure/px-storage-class.yaml
  drivers/scheduler/k8s/specs/nginx-fada-repl-vps/pure/px-storage-class.yaml
  drivers/scheduler/scheduler.go
  tests/basic/pure_test.go
Labels: ready-for-review

#2589 Automating KDMP backup failure
  go.mod
  go.sum
  tests/backup/backup_sanity_test.go
  tests/backup_helper.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/register.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/backuplocationmaintenance.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/dataexport.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/doc.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/register.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/resourcebackup.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/resourceexport.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/volumebackup.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/volumebackupdelete.go
  vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/doc.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/backuplocationmaintenance.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/dataexport.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/doc.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/generated_expansion.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/kdmp_client.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/resourcebackup.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/resourceexport.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/volumebackup.go
  vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/volumebackupdelete.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/backuplocationmaintenance.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/dataexport.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/kdmp.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/resourcebackup.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/resourceexport.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/volumebackup.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/volumebackupdelete.go
  vendor/modules.txt
Labels: ready-for-review, Px-Backup

#2588 Deploy apps which has different volumes at framework level
  drivers/scheduler/k8s/specs/pxb-multipleapp-multivol/mutiple_app_multivol.yaml
  drivers/scheduler/k8s/specs/pxb-singleapp-multivol/single_app_multivol.yaml
  tests/common.go
Labels: ready-for-review, Px-Backup

#2604 [PTX-24636] Fix createStorageObject
  drivers/scheduler/k8s/k8s.go
  drivers/volume/volume.go
Labels: ready-for-review

#2597 Helper methods to validate backup with partial success
  tests/backup_helper.go
Labels: ready-to-merge, ready-for-review, Px-Backup

#2598 Adding stop kubelet test
  drivers/node/aws/aws.go
  drivers/node/node.go
  drivers/node/ssh/ssh.go
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/eks/eks.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  drivers/volume/portworx/portworx.go
  pkg/stats/stats.go
  tests/basic/misc_test.go
  tests/basic/node_decommission_test.go
  tests/basic/storage_pool_test.go
  tests/basic/upgrade_cluster_test.go
  tests/common.go
  tests/longevity/longevity_helper.go
  tests/longevity/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review

#2610 Added new test BackupCSIVolumesWithPartialSuccess
  drivers/scheduler/dcos/dcos.go
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  tests/backup/backup_partial_test.go
  tests/backup/backup_test_labels.go
  tests/backup_helper.go
  tests/common.go
Labels: new-test, Px-Backup

#2591 PTX-23991 Deleting Pools after modifying STC with disabling CSI topology
  tests/basic/pure_test.go
Labels: ready-for-review

#2579 PB-7185: Add test to set namespace and cluster level PSA settings
  tests/backup/backup_psa_test.go
  tests/backup/backup_test_labels.go
  tests/backup_helper.go
  tests/common.go
Labels: ready-for-review, Px-Backup

#2621 Adding a new test case PartialBackupSuccessWithPxVolumes
  drivers/scheduler/k8s/specs/mysql-backup-data/px-mysql-app.yaml
  tests/backup/backup_partial_test.go
  tests/backup/backup_sanity_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2625 Fix AUTToggleautopilot
  tests/basic/autopilot_test.go
  tests/common.go
Labels: ready-for-review

#2611 Fixing OKE platform upgrade
  drivers/scheduler/oke/oke.go
  tests/basic/upgrade_cluster_test.go
Labels: ready-for-review

#2628 PB-7378: Add job pod app with restricted and other psa levels
  drivers/scheduler/k8s/specs/job-pod-deployer-psa-restricted/app.yaml
  drivers/scheduler/k8s/specs/job-pod-deployer-psa-restricted/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/job-pod-deployer-psa-restricted/storage.yaml
  drivers/scheduler/k8s/specs/job-pod-deployer/app.yaml
  drivers/scheduler/k8s/specs/job-pod-deployer/pxd/px-storage-class.yaml
  drivers/scheduler/k8s/specs/job-pod-deployer/storage.yaml
Labels: ready-for-review, Px-Backup

#2607 PTX-24561 To Test App in 3 diff combinations of Realm-pod,pod,and legacy deployment
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/scheduler.go
  tests/basic/pure_test.go
  tests/common.go
Labels: ready-for-review

#2636 Adding a new test case PartialBackupSuccessWithPxAndKDMPVolumes
  go.mod
  go.sum
  tests/backup/backup_partial_test.go
  tests/backup_helper.go
  vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go
  vendor/github.com/portworx/sched-ops/k8s/kdmp/dataexport.go
  vendor/github.com/rancher/rancher/pkg/client/generated/management/v3/zz_generated_pod_security_admission_configuration_template_defaults.go
  vendor/modules.txt
Labels: ready-for-review, Px-Backup

#2623 PSA Testcase automation : Restore from higher Privileged to lower Privileged namespace
  drivers/scheduler/k8s/specs/mysql-backup/px-mysql-app.yaml
  drivers/scheduler/k8s/specs/mysql-restricted/px-mysql-app.yaml
  tests/backup/backup_psa_test.go
  tests/backup/backup_test_labels.go
  tests/backup_helper.go
  tests/common.go
Labels: new-test, ready-for-review, Px-Backup

#2634 Added a new test case BackupStateTransitionForScheduledBackups
  tests/backup/backup_partial_test.go
  tests/backup/backup_test_labels.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup

#2633 Test Improvements for existing FA testcases
  tests/basic/pure_test.go
  tests/common.go
Labels: ready-for-review

#2626 Modified PX Backup upgrade TC to include partial success validation
  tests/backup/backup_upgrade_test.go
  tests/backup_helper.go
Labels: ready-for-review, Px-Backup
