Repository portworx/torpedo, pull requests merged in 2024-01, with the labels that each got.

#1948 Adding logic to update event stats to aetos
  drivers/scheduler/k8s/k8s.go
  drivers/scheduler/k8s/specs/kubevirt-cloudsnap/pvc-longevity-cloudsnap.yaml
  drivers/scheduler/k8s/specs/kubevirt-cloudsnap/pxd/sc-px-cloudsnap.yaml
  drivers/scheduler/k8s/specs/kubevirt-cloudsnap/vm-longevity-cloudsnap.yaml
  drivers/scheduler/k8s/specs/kubevirt-localsnap/pvc-longevity-localsnap.yaml
  drivers/scheduler/k8s/specs/kubevirt-localsnap/pxd/sc-px.yaml
  drivers/scheduler/k8s/specs/kubevirt-localsnap/vm-longevity-localsnap.yaml
  drivers/scheduler/k8s/specs/kubevirt-multi-disk/pvc-multi-disk.yaml
  drivers/scheduler/k8s/specs/kubevirt-multi-disk/pxd/sc-px-multi-disk.yaml
  drivers/scheduler/k8s/specs/kubevirt-multi-disk/vm-multi-disk.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-io/pvc-longevity-auto-journal-io-load.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-io/pvc-longevity-io-load.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-io/pxd/sc-auto-journal.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-io/pxd/sc-journal.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-io/vm-longevity-auto-journal-io-load.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-io/vm-longevity-io-load.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-vm/pvc-longevity-io.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-vm/pvc-longevity-simple-vm.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-vm/pxd/sc-px-csi.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-vm/pxd/sc-px-io.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-vm/vm-longevity-rwo-io.yaml
  drivers/scheduler/k8s/specs/kubevirt-ssie-vm/vm-ubuntu-longevity-simple-vm.yaml
  drivers/volume/portworx/schedops/k8s-schedops.go
  pkg/aetosutil/dashboardutil.go
  pkg/push_stats_reboot.go
  pkg/stats/stats.go
  tests/basic/longevity_test.go
  tests/basic/vcluster_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-for-review

#1992 PB-5282: Skip log collection in case of IBM and gke Provisioner
  tests/common.go
Labels: ready-for-review, Px-Backup

#2001 PB-5331: Add logic to remove backups with `DeleteBackupWithClusterUID()`
  tests/backup/backup_restore_basic_test.go
Labels: ready-for-review, Px-Backup

#2002 PTX-21279 Add more verbosity when validating mounts and devices
  drivers/volume/portworx/schedops/k8s-schedops.go
Labels: ready-for-review

#2003 Separated the postgres app specs for OCP and GKE
  drivers/scheduler/k8s/specs/postgres-cephfs-csi/ocp/cephfs-csi-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-cephfs-csi/postgres-csi-app.yaml
  drivers/scheduler/k8s/specs/postgres-cephfs-csi/storage.yaml
  drivers/scheduler/k8s/specs/postgres-csi/pso/pso-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-gce-pd/gce/gce-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-gce-pd/postgres-csi-app.yaml
  drivers/scheduler/k8s/specs/postgres-gce-pd/storage.yaml
  drivers/scheduler/k8s/specs/postgres-pd-csi-storage-gke/gce/gce-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-pd-csi-storage-gke/postgres-csi-app.yaml
  drivers/scheduler/k8s/specs/postgres-pd-csi-storage-gke/storage.yaml
  drivers/scheduler/k8s/specs/postgres-rbd-csi/ocp/rbd-csi-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-rbd-csi/postgres-csi-app.yaml
  drivers/scheduler/k8s/specs/postgres-rbd-csi/storage.yaml
  drivers/scheduler/k8s/specs/postgres-rgw-csi/ocp/rgw-csi-storage-class.yaml
  drivers/scheduler/k8s/specs/postgres-rgw-csi/postgres-csi-app.yaml
  drivers/scheduler/k8s/specs/postgres-rgw-csi/storage.yaml
Labels: ready-for-review, Px-Backup

#1997 PB-5203: Add code to remove namespaces at end of testcases
  tests/common.go
Labels: ready-to-merge, Px-Backup

#2006 Adding method for dumping anthos upgrade logs
  drivers/scheduler/anthos/anthos.go
Labels: ready-for-review

#2008 PB-5348: Add mysql-ibm app to run mysql app with ibm block vpc
  drivers/scheduler/k8s/specs/mysql-ibm/ibm/ibm-storage-class.yaml
  drivers/scheduler/k8s/specs/mysql-ibm/mysql-app.yaml
  drivers/scheduler/k8s/specs/mysql-ibm/mysql-storage.yaml
  tests/backup/backup_helper.go
Labels: ready-for-review, Px-Backup

#2017 PTX-21795 Add API acknowledgment for OCP 4.14 and improve logging
  drivers/scheduler/openshift/openshift.go
Labels: ready-for-review

#2018 PTX-21474 Install gcompat package to unblock OCP 4.14 CLI
  Dockerfile
Labels: ready-for-review

#1995 TC to remove cloud snapshots from NFS backup location and verify the backup status
  tests/backup/backup_nfs_test.go
Labels: ready-for-review, Px-Backup

#1998 Adding data integrity validation for PX upgrade test
  drivers/pds/lib/utils.go
  tests/basic/storage_pool_test.go
  tests/basic/upgrade_test.go
  tests/common.go
Labels: ready-for-review

#1771 [PTX-20500] TC Automation - AutoPoolExpandCrashTest
  drivers/volume/portworx/portworx.go
  tests/basic/autopilot_test.go
Labels: in-progress

#1956 Add framework support for injecting data in app pods while running system test
  drivers/applications/apptypes/appType.go
  drivers/applications/driver/driver.go
  drivers/applications/mysql/mysql.go
  drivers/applications/postgres/postgres.go
  drivers/backup/portworx/portworx.go
  drivers/scheduler/k8s/specs/mysql-backup/px-mysql-app.yaml
  drivers/scheduler/k8s/specs/postgres-backup/px-postgres-app.yaml
  drivers/scheduler/k8s/specs/postgres-csi/postgres-csi-app.yaml
  drivers/utilities/utilities.go
  go.mod
  tests/backup/backup_basic_test.go
  tests/backup/backup_delete_test.go
  tests/backup/backup_helper.go
  tests/backup/backup_kubevirt_test.go
  tests/backup/backup_license_test.go
  tests/backup/backup_locked_bucket_test.go
  tests/backup/backup_namespace_labelled_test.go
  tests/backup/backup_nfs_test.go
  tests/backup/backup_orphaned_test.go
  tests/backup/backup_portworx_test.go
  tests/backup/backup_rancher_test.go
  tests/backup/backup_resiliency_test.go
  tests/backup/backup_restore_basic_test.go
  tests/backup/backup_sanity_test.go
  tests/backup/backup_scale_test.go
  tests/backup/backup_sse_test.go
  tests/backup/backup_stork_test.go
  tests/backup/backup_upgrade_test.go
  tests/common.go
  vendor/github.com/go-sql-driver/mysql/.gitignore
  vendor/github.com/go-sql-driver/mysql/AUTHORS
  vendor/github.com/go-sql-driver/mysql/CHANGELOG.md
  vendor/github.com/go-sql-driver/mysql/LICENSE
  vendor/github.com/go-sql-driver/mysql/README.md
  vendor/github.com/go-sql-driver/mysql/auth.go
  vendor/github.com/go-sql-driver/mysql/buffer.go
  vendor/github.com/go-sql-driver/mysql/collations.go
  vendor/github.com/go-sql-driver/mysql/conncheck.go
  vendor/github.com/go-sql-driver/mysql/conncheck_dummy.go
  vendor/github.com/go-sql-driver/mysql/connection.go
  vendor/github.com/go-sql-driver/mysql/connector.go
  vendor/github.com/go-sql-driver/mysql/const.go
  vendor/github.com/go-sql-driver/mysql/driver.go
  vendor/github.com/go-sql-driver/mysql/dsn.go
  vendor/github.com/go-sql-driver/mysql/errors.go
  vendor/github.com/go-sql-driver/mysql/fields.go
  vendor/github.com/go-sql-driver/mysql/fuzz.go
  vendor/github.com/go-sql-driver/mysql/infile.go
  vendor/github.com/go-sql-driver/mysql/nulltime.go
  vendor/github.com/go-sql-driver/mysql/nulltime_go113.go
  vendor/github.com/go-sql-driver/mysql/nulltime_legacy.go
  vendor/github.com/go-sql-driver/mysql/packets.go
  vendor/github.com/go-sql-driver/mysql/result.go
  vendor/github.com/go-sql-driver/mysql/rows.go
  vendor/github.com/go-sql-driver/mysql/statement.go
  vendor/github.com/go-sql-driver/mysql/transaction.go
  vendor/github.com/go-sql-driver/mysql/utils.go
  vendor/modules.txt
Labels: ready-for-review, Px-Backup

#2021 PTX-21817 Change egrep to grep -E when checking for Telemetry status via pxctl
  tests/basic/telemetry_test.go
Labels: ready-for-review

#2025 Adding NFS proxy validation for longevity test
  tests/basic/longevity_test.go
  tests/basic/upgrade_test.go
Labels: ready-for-review

#2026 Change mysql spec to run with only one PVC
  drivers/scheduler/k8s/specs/mysql-ibm/mysql-app.yaml
  drivers/scheduler/k8s/specs/mysql-ibm/mysql-storage.yaml
Labels: ready-for-review, Px-Backup

#1738 [PTX-20498] Add ConfigMap support for Upgrade Endpoints
  tests/basic/longevity_test.go
  tests/testTriggers.go
Labels: ready-for-review, testing-in-progress

#2020 PWX-35639:Adding test for fuse driver failure
  drivers/scheduler/k8s/specs/fio-sharedv4/fio-config-map.yaml
  tests/basic/volume_ops_test.go
  tests/common.go
  tests/testTriggers.go
Labels: ready-for-review

#2022 PTX-21497 Fix for PKS diag directory
  drivers/volume/common.go
  drivers/volume/portworx/portworx.go
  drivers/volume/volume.go
  tests/basic/telemetry_test.go
Labels: ready-for-review

#2034 PTX-21984 Fix DS upgrades by skipping DMTHIN check
  tests/common.go
Labels: ready-for-review

#2023 PB-4792: Add test to backup & restore to locked bucket with shared objects
  tests/backup/backup_helper.go
  tests/backup/backup_kdmp_test.go
  tests/backup/backup_locked_bucket_test.go
  tests/backup/backup_namespace_labelled_test.go
  tests/backup/backup_nfs_test.go
  tests/backup/backup_orphaned_test.go
  tests/backup/backup_rbac_test.go
  tests/backup/backup_restore_basic_test.go
Labels: ready-for-review, Px-Backup

#2036 Fix the lib changes for gcp bucket level validation
  tests/backup/backup_orphaned_test.go
  tests/common.go
Labels: ready-for-review, Px-Backup, Lib
